---
title: "Data Cleaning"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, message=FALSE}
library(dplyr)
library(tidyr)
library(readr)
```

## Data sources

### Read in the data

```{r}
catch_original <- read_csv("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.302.1")

```

## Clean and Reshape Data

### Remove unnecessary columns

```{r, message=FALSE}

catch_data <- catch_original %>% 
  select(Region, Year, Chinook, Sockeye, Coho, Pink, Chum)

head(catch_data)
```

### Check column typing

```{r, message=FALSE}
catch_clean <- catch_data %>% 
  mutate(Chinook = ifelse(Chinook == "I", 1, Chinook)) %>%
  mutate(Chinook = as.integer(Chinook))

head(catch_clean)
```

### Reshape data

```{r}
catch_long= catch_clean %>% pivot_longer(cols=-c(Region, Year), names_to="species", values_to="catch")

head(catch_clean)
head(catch_long)
```

```{r}
catch_wide= catch_long %>% pivot_wider(names_from="species", values_from="catch")
head(catch_wide)
```

```{r}
catch_long = catch_long %>% rename(catch_thousands = catch)

catch_long = catch_long %>% mutate(catch = catch_thousands*1000) %>% select(-catch_thousands)

```


```{r}
 mean_region = catch_long %>% group_by(Region) %>% summarise(catch_mean = mean(catch)) %>% arrange(-catch_mean)
```

```{r}
n_region=catch_long %>%  group_by(Region) %>% summarise(n=n())
```

## Join to Regions dataset